# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# Categories
Category.create(name: 'Scrunchies', image: 'https://www.tresovejastejidos.com/wp-content/uploads/2020/08/c%C3%ADrculos-crochet-vuelta-4.jpg')
Category.create(name: 'Hogar & Deco', image: 'https://www.tresovejastejidos.com/wp-content/uploads/2020/08/c%C3%ADrculos-crochet-vuelta-4.jpg')
Category.create(name: 'Primavera & Verano', image: 'https://www.tresovejastejidos.com/wp-content/uploads/2020/08/c%C3%ADrculos-crochet-vuelta-4.jpg')
Category.create(name: 'Otoño & Invierno', image: 'https://www.tresovejastejidos.com/wp-content/uploads/2020/08/c%C3%ADrculos-crochet-vuelta-4.jpg')
Category.create(name: 'Toallas & Discos', image: 'https://www.tresovejastejidos.com/wp-content/uploads/2020/08/c%C3%ADrculos-crochet-vuelta-4.jpg')
Category.create(name: 'Bolsos & Neceseres', image: 'https://www.tresovejastejidos.com/wp-content/uploads/2020/08/c%C3%ADrculos-crochet-vuelta-4.jpg')
Category.create(name: 'Muñecos', image: 'https://www.tresovejastejidos.com/wp-content/uploads/2020/08/c%C3%ADrculos-crochet-vuelta-4.jpg')

# Dummy reviews
Review.create(user_name: 'Alejo Yanczuk', product_name: 'Abejita Rosa', content: 'Lorem ipsum lorem ipsum ipsum jklhasdjkasd jk jklasjkjaj jklajksljklasdjjkajklsd', images: 'https://i.postimg.cc/1XYK97DH/IMG-8796.jpg')
Review.create(user_name: 'Alejo Yanczuk', product_name: 'Abejita Rosa', content: 'Lorem ipsum lorem ipsum ipsum jklhasdjkasd jk jklasjkjaj jklajksljklasdjjkajklsd', images: 'https://i.postimg.cc/1XYK97DH/IMG-8796.jpg')
Review.create(user_name: 'Alejo Yanczuk', product_name: 'Abejita Rosa', content: 'Lorem ipsum lorem ipsum ipsum jklhasdjkasd jk jklasjkjaj jklajksljklasdjjkajklsd', images: 'https://i.postimg.cc/1XYK97DH/IMG-8796.jpg')
Review.create(user_name: 'Alejo Yanczuk', product_name: 'Abejita Rosa', content: 'Lorem ipsum lorem ipsum ipsum jklhasdjkasd jk jklasjkjaj jklajksljklasdjjkajklsd', images: 'https://i.postimg.cc/1XYK97DH/IMG-8796.jpg')
Review.create(user_name: 'Alejo Yanczuk', product_name: 'Abejita Rosa', content: 'Lorem ipsum lorem ipsum ipsum jklhasdjkasd jk jklasjkjaj jklajksljklasdjjkajklsd', images: 'https://i.postimg.cc/1XYK97DH/IMG-8796.jpg')
Review.create(user_name: 'Alejo Yanczuk', product_name: 'Abejita Rosa', content: 'Lorem ipsum lorem ipsum ipsum jklhasdjkasd jk jklasjkjaj jklajksljklasdjjkajklsd', images: 'https://i.postimg.cc/1XYK97DH/IMG-8796.jpg')
Review.create(user_name: 'Alejo Yanczuk', product_name: 'Abejita Rosa', content: 'Lorem ipsum lorem ipsum ipsum jklhasdjkasd jk jklasjkjaj jklajksljklasdjjkajklsd', images: 'https://i.postimg.cc/1XYK97DH/IMG-8796.jpg')
Review.create(user_name: 'Alejo Yanczuk', product_name: 'Abejita Rosa', content: 'Lorem ipsum lorem ipsum ipsum jklhasdjkasd jk jklasjkjaj jklajksljklasdjjkajklsd', images: 'https://i.postimg.cc/1XYK97DH/IMG-8796.jpg')
Review.create(user_name: 'Alejo Yanczuk', product_name: 'Abejita Rosa', content: 'Lorem ipsum lorem ipsum ipsum jklhasdjkasd jk jklasjkjaj jklajksljklasdjjkajklsd', images: 'https://i.postimg.cc/1XYK97DH/IMG-8796.jpg')
Review.create(user_name: 'Alejo Yanczuk', product_name: 'Abejita Rosa', content: 'Lorem ipsum lorem ipsum ipsum jklhasdjkasd jk jklasjkjaj jklajksljklasdjjkajklsd', images: 'https://i.postimg.cc/1XYK97DH/IMG-8796.jpg')
Review.create(user_name: 'Alejo Yanczuk', product_name: 'Abejita Rosa', content: 'Lorem ipsum lorem ipsum ipsum jklhasdjkasd jk jklasjkjaj jklajksljklasdjjkajklsd', images: 'https://i.postimg.cc/1XYK97DH/IMG-8796.jpg')
Review.create(user_name: 'Alejo Yanczuk', product_name: 'Abejita Rosa', content: 'Lorem ipsum lorem ipsum ipsum jklhasdjkasd jk jklasjkjaj jklajksljklasdjjkajklsd', images: 'https://i.postimg.cc/1XYK97DH/IMG-8796.jpg')
Review.create(user_name: 'Alejo Yanczuk', product_name: 'Abejita Rosa', content: 'Lorem ipsum lorem ipsum ipsum jklhasdjkasd jk jklasjkjaj jklajksljklasdjjkajklsd', images: 'https://i.postimg.cc/1XYK97DH/IMG-8796.jpg')
Review.create(user_name: 'Alejo Yanczuk', product_name: 'Abejita Rosa', content: 'Lorem ipsum lorem ipsum ipsum jklhasdjkasd jk jklasjkjaj jklajksljklasdjjkajklsd', images: 'https://i.postimg.cc/1XYK97DH/IMG-8796.jpg')
Review.create(user_name: 'Alejo Yanczuk', product_name: 'Abejita Rosa', content: 'Lorem ipsum lorem ipsum ipsum jklhasdjkasd jk jklasjkjaj jklajksljklasdjjkajklsd', images: 'https://i.postimg.cc/1XYK97DH/IMG-8796.jpg')
Review.create(user_name: 'Alejo Yanczuk', product_name: 'Abejita Rosa', content: 'Lorem ipsum lorem ipsum ipsum jklhasdjkasd jk jklasjkjaj jklajksljklasdjjkajklsd', images: 'https://i.postimg.cc/1XYK97DH/IMG-8796.jpg')
Review.create(user_name: 'Alejo Yanczuk', product_name: 'Abejita Rosa', content: 'Lorem ipsum lorem ipsum ipsum jklhasdjkasd jk jklasjkjaj jklajksljklasdjjkajklsd', images: 'https://i.postimg.cc/1XYK97DH/IMG-8796.jpg')
Review.create(user_name: 'Alejo Yanczuk', product_name: 'Abejita Rosa', content: 'Lorem ipsum lorem ipsum ipsum jklhasdjkasd jk jklasjkjaj jklajksljklasdjjkajklsd', images: 'https://i.postimg.cc/1XYK97DH/IMG-8796.jpg')
Review.create(user_name: 'Alejo Yanczuk', product_name: 'Abejita Rosa', content: 'Lorem ipsum lorem ipsum ipsum jklhasdjkasd jk jklasjkjaj jklajksljklasdjjkajklsd', images: 'https://i.postimg.cc/1XYK97DH/IMG-8796.jpg')
Review.create(user_name: 'Alejo Yanczuk', product_name: 'Abejita Rosa', content: 'Lorem ipsum lorem ipsum ipsum jklhasdjkasd jk jklasjkjaj jklajksljklasdjjkajklsd', images: 'https://i.postimg.cc/1XYK97DH/IMG-8796.jpg')
Review.create(user_name: 'Alejo Yanczuk', product_name: 'Abejita Rosa', content: 'Lorem ipsum lorem ipsum ipsum jklhasdjkasd jk jklasjkjaj jklajksljklasdjjkajklsd', images: 'https://i.postimg.cc/1XYK97DH/IMG-8796.jpg')
Review.create(user_name: 'Alejo Yanczuk', product_name: 'Abejita Rosa', content: 'Lorem ipsum lorem ipsum ipsum jklhasdjkasd jk jklasjkjaj jklajksljklasdjjkajklsd', images: 'https://i.postimg.cc/1XYK97DH/IMG-8796.jpg')
Review.create(user_name: 'Alejo Yanczuk', product_name: 'Abejita Rosa', content: 'Lorem ipsum lorem ipsum ipsum jklhasdjkasd jk jklasjkjaj jklajksljklasdjjkajklsd', images: 'https://i.postimg.cc/1XYK97DH/IMG-8796.jpg')
Review.create(user_name: 'Alejo Yanczuk', product_name: 'Abejita Rosa', content: 'Lorem ipsum lorem ipsum ipsum jklhasdjkasd jk jklasjkjaj jklajksljklasdjjkajklsd', images: 'https://i.postimg.cc/1XYK97DH/IMG-8796.jpg')
Review.create(user_name: 'Alejo Yanczuk', product_name: 'Abejita Rosa', content: 'Lorem ipsum lorem ipsum ipsum jklhasdjkasd jk jklasjkjaj jklajksljklasdjjkajklsd', images: 'https://i.postimg.cc/1XYK97DH/IMG-8796.jpg')
Review.create(user_name: 'Alejo Yanczuk', product_name: 'Abejita Rosa', content: 'Lorem ipsum lorem ipsum ipsum jklhasdjkasd jk jklasjkjaj jklajksljklasdjjkajklsd', images: 'https://i.postimg.cc/1XYK97DH/IMG-8796.jpg')
Review.create(user_name: 'Alejo Yanczuk', product_name: 'Abejita Rosa', content: 'Lorem ipsum lorem ipsum ipsum jklhasdjkasd jk jklasjkjaj jklajksljklasdjjkajklsd', images: 'https://i.postimg.cc/1XYK97DH/IMG-8796.jpg')
Review.create(user_name: 'Alejo Yanczuk', product_name: 'Abejita Rosa', content: 'Lorem ipsum lorem ipsum ipsum jklhasdjkasd jk jklasjkjaj jklajksljklasdjjkajklsd', images: 'https://i.postimg.cc/1XYK97DH/IMG-8796.jpg')
Review.create(user_name: 'Alejo Yanczuk', product_name: 'Abejita Rosa', content: 'Lorem ipsum lorem ipsum ipsum jklhasdjkasd jk jklasjkjaj jklajksljklasdjjkajklsd', images: 'https://i.postimg.cc/1XYK97DH/IMG-8796.jpg')
Review.create(user_name: 'Alejo Yanczuk', product_name: 'Abejita Rosa', content: 'Lorem ipsum lorem ipsum ipsum jklhasdjkasd jk jklasjkjaj jklajksljklasdjjkajklsd', images: 'https://i.postimg.cc/1XYK97DH/IMG-8796.jpg')
Review.create(user_name: 'Alejo Yanczuk', product_name: 'Abejita Rosa', content: 'Lorem ipsum lorem ipsum ipsum jklhasdjkasd jk jklasjkjaj jklajksljklasdjjkajklsd', images: 'https://i.postimg.cc/1XYK97DH/IMG-8796.jpg')
Review.create(user_name: 'Alejo Yanczuk', product_name: 'Abejita Rosa', content: 'Lorem ipsum lorem ipsum ipsum jklhasdjkasd jk jklasjkjaj jklajksljklasdjjkajklsd', images: 'https://i.postimg.cc/1XYK97DH/IMG-8796.jpg')
Review.create(user_name: 'Alejo Yanczuk', product_name: 'Abejita Rosa', content: 'Lorem ipsum lorem ipsum ipsum jklhasdjkasd jk jklasjkjaj jklajksljklasdjjkajklsd', images: 'https://i.postimg.cc/1XYK97DH/IMG-8796.jpg')
Review.create(user_name: 'Alejo Yanczuk', product_name: 'Abejita Rosa', content: 'Lorem ipsum lorem ipsum ipsum jklhasdjkasd jk jklasjkjaj jklajksljklasdjjkajklsd', images: 'https://i.postimg.cc/1XYK97DH/IMG-8796.jpg')
Review.create(user_name: 'Alejo Yanczuk', product_name: 'Abejita Rosa', content: 'Lorem ipsum lorem ipsum ipsum jklhasdjkasd jk jklasjkjaj jklajksljklasdjjkajklsd', images: 'https://i.postimg.cc/1XYK97DH/IMG-8796.jpg')
Review.create(user_name: 'Alejo Yanczuk', product_name: 'Abejita Rosa', content: 'Lorem ipsum lorem ipsum ipsum jklhasdjkasd jk jklasjkjaj jklajksljklasdjjkajklsd', images: 'https://i.postimg.cc/1XYK97DH/IMG-8796.jpg')
Review.create(user_name: 'Alejo Yanczuk', product_name: 'Abejita Rosa', content: 'Lorem ipsum lorem ipsum ipsum jklhasdjkasd jk jklasjkjaj jklajksljklasdjjkajklsd', images: 'https://i.postimg.cc/1XYK97DH/IMG-8796.jpg')
Review.create(user_name: 'Alejo Yanczuk', product_name: 'Abejita Rosa', content: 'Lorem ipsum lorem ipsum ipsum jklhasdjkasd jk jklasjkjaj jklajksljklasdjjkajklsd', images: 'https://i.postimg.cc/1XYK97DH/IMG-8796.jpg')
Review.create(user_name: 'Alejo Yanczuk', product_name: 'Abejita Rosa', content: 'Lorem ipsum lorem ipsum ipsum jklhasdjkasd jk jklasjkjaj jklajksljklasdjjkajklsd', images: 'https://i.postimg.cc/1XYK97DH/IMG-8796.jpg')
Review.create(user_name: 'Alejo Yanczuk', product_name: 'Abejita Rosa', content: 'Lorem ipsum lorem ipsum ipsum jklhasdjkasd jk jklasjkjaj jklajksljklasdjjkajklsd', images: 'https://i.postimg.cc/1XYK97DH/IMG-8796.jpg')
Review.create(user_name: 'Alejo Yanczuk', product_name: 'Abejita Rosa', content: 'Lorem ipsum lorem ipsum ipsum jklhasdjkasd jk jklasjkjaj jklajksljklasdjjkajklsd', images: 'https://i.postimg.cc/1XYK97DH/IMG-8796.jpg')
Review.create(user_name: 'Alejo Yanczuk', product_name: 'Abejita Rosa', content: 'Lorem ipsum lorem ipsum ipsum jklhasdjkasd jk jklasjkjaj jklajksljklasdjjkajklsd', images: 'https://i.postimg.cc/1XYK97DH/IMG-8796.jpg')
Review.create(user_name: 'Alejo Yanczuk', product_name: 'Abejita Rosa', content: 'Lorem ipsum lorem ipsum ipsum jklhasdjkasd jk jklasjkjaj jklajksljklasdjjkajklsd', images: 'https://i.postimg.cc/1XYK97DH/IMG-8796.jpg')
Review.create(user_name: 'Alejo Yanczuk', product_name: 'Abejita Rosa', content: 'Lorem ipsum lorem ipsum ipsum jklhasdjkasd jk jklasjkjaj jklajksljklasdjjkajklsd', images: 'https://i.postimg.cc/1XYK97DH/IMG-8796.jpg')
Review.create(user_name: 'Alejo Yanczuk', product_name: 'Abejita Rosa', content: 'Lorem ipsum lorem ipsum ipsum jklhasdjkasd jk jklasjkjaj jklajksljklasdjjkajklsd', images: 'https://i.postimg.cc/1XYK97DH/IMG-8796.jpg')
Review.create(user_name: 'Alejo Yanczuk', product_name: 'Abejita Rosa', content: 'Lorem ipsum lorem ipsum ipsum jklhasdjkasd jk jklasjkjaj jklajksljklasdjjkajklsd', images: 'https://i.postimg.cc/1XYK97DH/IMG-8796.jpg')
Review.create(user_name: 'Alejo Yanczuk', product_name: 'Abejita Rosa', content: 'Lorem ipsum lorem ipsum ipsum jklhasdjkasd jk jklasjkjaj jklajksljklasdjjkajklsd', images: 'https://i.postimg.cc/1XYK97DH/IMG-8796.jpg')
Review.create(user_name: 'Alejo Yanczuk', product_name: 'Abejita Rosa', content: 'Lorem ipsum lorem ipsum ipsum jklhasdjkasd jk jklasjkjaj jklajksljklasdjjkajklsd', images: 'https://i.postimg.cc/1XYK97DH/IMG-8796.jpg')

